version: '2'

volumes:
  media:

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
  api:
    build: ./backend
    ports:
      - 3535:3535
    volumes:
      - media:/media
  nginx-rtmp:
    build: ./docker-nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    volumes:
      - media:/tmp/hls
    environment:
      HTTP_PORT: 80
      RTMP_PORT: 1935
      API_SERVER: api