version: '2'

volumes:
  media:

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - network
  api:
    build: ./backend
    ports:
      - 3535:3535
    volumes:
      - media:/app/media
      # - ~/Desktop/project/ts-stream/backend/index.js:/app/index.js
    networks:
      - network
  nginx-rtmp:
    build: ./docker-nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    volumes:
      - media:/opt/data/hls
    networks:
      - network
    environment:
      HTTP_PORT: 80
      RTMP_PORT: 1935
      API_SERVER: api
  nginx-reverse:
    build: ./nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    environment:
      SERVER_NAME: localhost
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"
          gateway: 172.23.0.1